#!/bin/bash

. "${PWD}/.setenv"

# initialise rolespec
. "${ROLESPEC_LIB}/main"

# install specific version of ansible
#install_ansible "v2.4.0"


## place to prepare test, specify needed apps and configurations
# i.e.: apt-get update \
#       && apt-get install -y vim git sudo \
#       && echo "ansible  ALL=(ALL)   NOPASSWD:ALL" > /etc/sudoers.d/ansible \
#       && useradd -d /home/ansible -m -s /bin/bash ansible
if [ ! -f "roles" ]; then
	ln -s ${ROLES_HOME} ./roles 

	##for debug only...
	if [[ -n "${DEBUG}" ]]; then
		ls -l --color=auto
	fi
fi


# check syntax first, and then that the playbook runs
if [[ -n "${ANSIBLE_TRACE}" ]]; then
	assert_playbook_runs -vvvv  ## could also run in debug mode if needed
else
	assert_playbook_runs
fi


# check that tha playbook is idempotent
assert_playbook_idempotent


## place to verify the result(s) of the test(s)
# i.e.: assert_path /home/ansible/workspace
assert_path /opt/rancher-v0.6.5
assert_permission /opt/rancher-v0.6.5/rancher 755
assert_path /usr/local/bin/rancher


## place to specify tear down actions
# i.e.: userdel ansible
if [ -f "roles" ]; then
	unkink ./roles
fi
